package com.example.ui

object LocaleStrings {
    fun get(key: String, lang: AppLanguage): String {
        val dict = when(lang) {
            AppLanguage.EN -> mapOf(
                "app_title" to "OBD Cockpit Dashboard",
                "select_car_title" to "Select Your Car Type",
                "select_car_subtitle" to "Choose a profile to calibrate sensors & safety alert limits:",
                "sedan" to "Berline (Sedan)",
                "hatchback" to "Citadine (Hatchback)",
                "suv" to "SUV / 4x4",
                "electric" to "Electric Vehicle (EV)",
                "sports" to "Sport Driving Coupe",
                "obd_status" to "OBD Bluetooth status",
                "connected" to "OBD-II Connected",
                "connecting" to "Handshaking serial protocols...",
                "disconnected" to "OBD-II Bluetooth Disconnected",
                "active_device" to "Active device",
                "tap_to_search" to "Tap to connect diagnostic adaptor",
                "instruments" to "INSTRUMENTS COCKPIT",
                "coolant" to "Coolant Temperature",
                "coolant_desc" to "Normal range is 85-95°C",
                "battery" to "Battery Voltage",
                "battery_desc" to "Alternator active state",
                "fuel_rate" to "Fuel Consumption Flow",
                "fuel_rate_desc" to "Live OBD injection flow",
                "throttle" to "Throttle Position",
                "throttle_desc" to "Pedal angle indicator",
                "tires" to "TIRE PRESSURE TELEMETRY (BAR)",
                "tire_front_left" to "Front Left",
                "tire_front_right" to "Front Right",
                "tire_rear_left" to "Rear Left",
                "tire_rear_right" to "Rear Right",
                "quick_test" to "OBD Simulation Quick Controls:",
                "drop_tires" to "Drop Tires",
                "inflate_tires" to "Standard Tires",
                "dashboard" to "Dashboard",
                "maint_tab" to "Maintenance",
                "trips_tab" to "Trajets / Trips",
                "reports_tab" to "Reports",
                "settings_tab" to "Settings",
                "low_tire_alert" to "Low Tire Status Alert",
                "low_battery_alert" to "Low AGM Battery Voltage",
                "maintenance_required" to "Maintenance Required Soon",
                // Logbook translation
                "add_service" to "Log New Maintenance",
                "total_services" to "Logged services",
                "total_spent" to "Total Spent",
                "fuel_cost_auto" to "Automatically monitors cost summaries",
                "title_label" to "Intervention/Service Title",
                "category_label" to "Category",
                "cost_label" to "Cost Amount (DA)",
                "mileage_label" to "Odometer (km)",
                "notes_label" to "Additional notes...",
                "save_btn" to "Save Service Offline",
                "no_services" to "No recorded logs yet. Tap + to add first entry.",
                // Trips travel
                "active_trip" to "Active GPS tracking drive profile",
                "start_trip_btn" to "Start GPS Drive",
                "stop_trip_btn" to "Stop and Log Drive",
                "trip_dist" to "Drive Distance",
                "trip_dur" to "Elapsed Duration",
                "trip_fuel" to "Fuel Consumed",
                "gps_points_connected" to "GPS telemetry sequence locks active",
                "trip_history" to "Completed Trip History logs (Offline)",
                "no_trips" to "No completed drives recorded yet.",
                "avg_speed" to "Avg Speed",
                "max_speed" to "Max Speed",
                "from" to "From",
                "to" to "To",
                "delete" to "Delete",
                // Reports
                "perf_report" to "Monthly Performance Diagnostics",
                "fuel_eff" to "Fuel Efficiency Summary",
                "repair_costs" to "Accumulated Repairs",
                "diagnostic_trouble_codes" to "Engine ECU Trouble Radar",
                "scan_ecu" to "Trigger ECU OBD Scan",
                "scanning" to "Probing active diagnostic fault codes...",
                "clear_codes" to "Wipe OBD Troubles",
                "no_dtc" to "Systems healthy. No DTC faults mapped in ECU.",
                "export_report" to "Export CSV Report",
                "export_success" to "CSV report exported to local storage",
                // Settings
                "language_selection" to "App Localization Language",
                "prefer_french" to "Changer en Français 🇫🇷",
                "prefer_english" to "Switch to English 🇬🇧",
                "prefer_arabic" to "Switch to Arabic 🇩🇿",
                "car_manufacturer" to "Vehicle Manufacturer",
                "car_model" to "Vehicle Model",
                "car_manufacturer_placeholder" to "Enter manufacturer (e.g. Toyota, Lifan, Renault)",
                "car_model_placeholder" to "Enter model (e.g. Yaris, 520, Clio)",
                "theme_selection" to "App View Theme Mode",
                "dark_mode" to "Sporty Dark Mode",
                "light_mode" to "Clear Light Mode",
                "safety_thresholds" to "Customize Safety Alert Limits",
                "min_tire_p" to "Minimum Tire Pressure (Bar)",
                "min_batt_v" to "Minimum Battery Voltage (V)",
                "max_oil" to "Oil Change Odometer Range (km)",
                "cloud_sync" to "Cloud Platform Core Synchronization",
                "last_synced" to "Server Timestamp",
                "sync_btn" to "Sync Devices Now",
                "car_chassis_profile" to "Active Vehicle Profile"
            )
            AppLanguage.FR -> mapOf(
                "app_title" to "Tableau de Bord OBD",
                "select_car_title" to "Sélectionnez votre type de voiture",
                "select_car_subtitle" to "Choisissez un profil de châssis pour recalibrer les alertes :",
                "sedan" to "Berline standard",
                "hatchback" to "Citadine compacte",
                "suv" to "SUV / Break / 4x4",
                "electric" to "Véhicule Électrique (VE)",
                "sports" to "Coupé Sportif",
                "obd_status" to "Statut Bluetooth OBD",
                "connected" to "Module OBD-II Connecté",
                "connecting" to "Test d'initialisation série...",
                "disconnected" to "Fiche OBD-II Déconnectée",
                "active_device" to "Appareil actif",
                "tap_to_search" to "Rechercher la prise diagnostique",
                "instruments" to "COCKPIT INSTRUMENTS",
                "coolant" to "Température Refroidissement",
                "coolant_desc" to "Cible optimale de fonctionnement (85-95°C)",
                "battery" to "Tension Batterie",
                "battery_desc" to "Alternateur de bord",
                "fuel_rate" to "Injection Carburant",
                "fuel_rate_desc" to "Débit calculé en direct",
                "throttle" to "Ouverture Papillon",
                "throttle_desc" to "Position d'accélération",
                "tires" to "TÉLÉMÉTRIE PRESSION DES PNEUS (BAR)",
                "tire_front_left" to "Avant Gauche",
                "tire_front_right" to "Avant Droit",
                "tire_rear_left" to "Arrière Gauche",
                "tire_rear_right" to "Arrière Droit",
                "quick_test" to "Contrôles de Simulation OBD :",
                "drop_tires" to "Dégonfler Pneus",
                "inflate_tires" to "Pneus Normaux",
                "dashboard" to "Tableau de bord",
                "maint_tab" to "Entretien",
                "trips_tab" to "Trajets",
                "reports_tab" to "Rapports",
                "settings_tab" to "Options",
                "low_tire_alert" to "Alerte de sous-pression pneus",
                "low_battery_alert" to "Tension batterie critique",
                "maintenance_required" to "Maintenance requise bientôt",
                "add_service" to "Ajouter Intervention",
                "total_services" to "Interventions stockées",
                "total_spent" to "Total Dépenses",
                "fuel_cost_auto" to "Calcule les frais d'entretien automatiquement",
                "title_label" to "Intitulé de l'intervention",
                "category_label" to "Catégorie",
                "cost_label" to "Coût de la prestation (DA)",
                "mileage_label" to "Kilométrage actuel (km)",
                "notes_label" to "Notes et détails...",
                "save_btn" to "Sauvegarder l'entrée",
                "no_services" to "Aucun carnet d'entretien. Cliquez sur + pour ajouter.",
                "active_trip" to "Suivi de trajet GPS actif",
                "start_trip_btn" to "Démarrer trajet",
                "stop_trip_btn" to "Consigner le trajet GPS",
                "trip_dist" to "Distance estimée",
                "trip_dur" to "Durée du trajet",
                "trip_fuel" to "Consommation fuel",
                "gps_points_connected" to "Coordonnées de l'antenne GPS verrouillat",
                "trip_history" to "Historique des Trajets Sauvés",
                "no_trips" to "Aucun trajet enregistré dans le journal local.",
                "avg_speed" to "Vitesse moy.",
                "max_speed" to "Vitesse max",
                "from" to "Départ",
                "to" to "Arrivée",
                "delete" to "Supprimer",
                "perf_report" to "Bilan Mensuel des Performances",
                "fuel_eff" to "Rapport d'Efficacité Énergétique",
                "repair_costs" to "Coûts de Réparation Cumulés",
                "diagnostic_trouble_codes" to "Codes d'erreurs OBD moteur (DTC)",
                "scan_ecu" to "Démarrer scanner ECU",
                "scanning" to "Consultation des pannes de bord...",
                "clear_codes" to "Effacer les alarmes OBD",
                "no_dtc" to "Calculateur sain. Aucun code panne de l'ECU.",
                "export_report" to "Exporter Historique CSV",
                "export_success" to "Fichier d'entretien CSV téléchargé !",
                "language_selection" to "Langue de l'application",
                "prefer_french" to "Passer en Français 🇫🇷",
                "prefer_english" to "Switch to English 🇬🇧",
                "prefer_arabic" to "Passer en Arabe 🇩🇿",
                "car_manufacturer" to "Constructeur / Marque",
                "car_model" to "Modèle du véhicule",
                "car_manufacturer_placeholder" to "Ex: Toyota, Lifan, Renault",
                "car_model_placeholder" to "Ex: Yaris, 520, Clio",
                "theme_selection" to "Mode de Thème de l'App",
                "dark_mode" to "Mode Sombre Sportif",
                "light_mode" to "Mode Clair Épuré",
                "safety_thresholds" to "Seuils d'alertes personnalisables",
                "min_tire_p" to "Pression pneus minimum (Bar)",
                "min_batt_v" to "Tension batterie minimum (V)",
                "max_oil" to "Seuil vidange moteur (km)",
                "cloud_sync" to "Synchronisation cloud multiplateforme",
                "last_synced" to "Dernière sauvegarde",
                "sync_btn" to "Forcer la synchronisation",
                "car_chassis_profile" to "Profil de châssis actif"
            )
            AppLanguage.AR -> mapOf(
                "app_title" to "لوحة تحكم OBD",
                "select_car_title" to "حدد نوع سيارتك",
                "select_car_subtitle" to "اختر نوع سيارة لمعايرة الحساسات وحدود تنبيه الأمان:",
                "sedan" to "صالون (سيدان)",
                "hatchback" to "هاتشباك (Citadine)",
                "suv" to "سيارة رياضية متعددة الاستخدامات (SUV)",
                "electric" to "سيارة كهربائية (EV)",
                "sports" to "سيارة رياضية كوبيه",
                "obd_status" to "حالة بلوتوث OBD",
                "connected" to "OBD-II متصل",
                "connecting" to "جاري الاتصال ببروتوكولات OBD...",
                "disconnected" to "OBD-II بلوتوث غير متصل",
                "active_device" to "الجهاز النشط",
                "tap_to_search" to "انقر لتوصيل محول التشخيص",
                "instruments" to "لوحة العدادات",
                "coolant" to "حرارة سائل التبريد",
                "coolant_desc" to "المعدل الطبيعي 85-95 درجة مئوية",
                "battery" to "جهد البطارية",
                "battery_desc" to "حالة المولد النشط",
                "fuel_rate" to "معدل استهلاك الوقود",
                "fuel_rate_desc" to "معدل الضخ المباشر من OBD",
                "throttle" to "موقع صمام الخانق",
                "throttle_desc" to "مؤشر زاوية دواسة الوقود",
                "tires" to "ضغط الإطارات بالبار (BAR)",
                "tire_front_left" to "الأمامي الأيسر",
                "tire_front_right" to "الأمامي الأيمن",
                "tire_rear_left" to "الخلفي الأيسر",
                "tire_rear_right" to "الخلفي الأيمن",
                "quick_test" to "عناصر التحكم السريع لمحاكاة OBD:",
                "drop_tires" to "تخفيض الضغط",
                "inflate_tires" to "إطارات طبيعية",
                "dashboard" to "الرئيسية",
                "maint_tab" to "الصيانة",
                "trips_tab" to "الرحلات",
                "reports_tab" to "التقارير",
                "settings_tab" to "الخيارات",
                "low_tire_alert" to "تنبيه انخفاض ضغط الإطارات",
                "low_battery_alert" to "تنبيه انخفاض جهد البطارية",
                "maintenance_required" to "مطلوب صيانة قريبا",
                "add_service" to "تسجيل صيانة جديدة",
                "total_services" to "الخدمات المسجلة",
                "total_spent" to "إجمالي المصاريف",
                "fuel_cost_auto" to "تحليل تلقائي للنفقات",
                "title_label" to "عنوان التدخل والصيانة",
                "category_label" to "الفئة",
                "cost_label" to "تكلفة الخدمة (د.ج)",
                "mileage_label" to "عداد المسافات الحالي (كم)",
                "notes_label" to "ملاحظات وتفاصيل إضافية...",
                "save_btn" to "حفظ الخدمة محلياً",
                "no_services" to "لا توجد خدمات مسجلة بعد. اضغط + للإضافة.",
                "active_trip" to "تتبع حركة نظام الـ GPS النشط",
                "start_trip_btn" to "بدء الرحلة بالـ GPS",
                "stop_trip_btn" to "إيقاف وحفظ الرحلة",
                "trip_dist" to "مسافة الرحلة",
                "trip_dur" to "مدة الرحلة",
                "trip_fuel" to "الوقود المستهلك",
                "gps_points_connected" to "تأمين اتصال نقاط GPS نشط",
                "trip_history" to "سجل الرحلات المكتملة",
                "no_trips" to "لا توجد رحلات مسجلة في الذاكرة المحلية.",
                "avg_speed" to "متوسط السرعة",
                "max_speed" to "السرعة القصوى",
                "from" to "المصدر / البداية",
                "to" to "الوجهة / النهاية",
                "delete" to "حذف",
                "perf_report" to "تقرير تشخيص الأداء الشهري",
                "fuel_eff" to "ملخص كفاءة الوقود",
                "repair_costs" to "تكاليف الإصلاح المتراكمة",
                "diagnostic_trouble_codes" to "رموز أعطال كمبيوتر السيارة (DTC)",
                "scan_ecu" to "فحص كمبيوتر السيارة OBD",
                "scanning" to "جاري قراءة أكواد الأعطال في السيارة...",
                "clear_codes" to "مسح أكواد الأعطال",
                "no_dtc" to "السيارة سليمة تماماً. لا توجد أعطال حالية.",
                "export_report" to "تصدير تقرير CSV",
                "export_success" to "تم تصدير ملف CSV بنجاح لوحدة التخزين!",
                "language_selection" to "لغة التطبيق",
                "prefer_french" to "Changer en Français 🇫🇷",
                "prefer_english" to "Switch to English 🇬🇧",
                "prefer_arabic" to "تغيير إلى العربية 🇩🇿",
                "car_manufacturer" to "الماركة / المصنع",
                "car_model" to "موديل السيارة",
                "car_manufacturer_placeholder" to "مثال: Toyota، Lifan، Renault",
                "car_model_placeholder" to "مثال: Yaris، 520، Clio",
                "theme_selection" to "مظهر واجهة التطبيق",
                "dark_mode" to "الوضعية الليلية (داكن)",
                "light_mode" to "الوضعية النهارية (مضيء)",
                "safety_thresholds" to "حدود تنبيهات الأمان المخصصة",
                "min_tire_p" to "الحد الأدنى لضغط العجلات (بار)",
                "min_batt_v" to "الحد الأدنى لجهد البطارية (فولت)",
                "max_oil" to "المسافة القصوى لتغيير الزيت (كم)",
                "cloud_sync" to "مزامنة البيانات على السحابة",
                "last_synced" to "آخر مزامنة ناجحة",
                "sync_btn" to "مزامنة البيانات الآن",
                "car_chassis_profile" to "ملف السيارة النشط"
            )
        }
        return dict[key] ?: key
    }
}
